'use client'

import {
    Card,
    CardContent,
    CardDescription,
    CardHeader,
    CardTitle,
} from '@/components/ui/card'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
    FileTextIcon,
    ClockIcon,
    CheckCircleIcon,
    AlertCircleIcon,
    PlusIcon,
    DownloadIcon,
    EyeIcon,
} from 'lucide-react'

const mockReports = [
    {
        id: 'rep_001',
        title: 'Quantum Computing in Cryptography Analysis',
        status: 'completed',
        createdAt: '2026-01-20 10:30 AM',
        agentsUsed: ['Assistant', 'Scrapper', 'Data Analyzer', 'Writer'],
        pages: 12,
    },
    {
        id: 'rep_002',
        title: 'Renewable Energy Storage Trends 2026',
        status: 'in_progress',
        createdAt: '2026-01-22 09:15 AM',
        agentsUsed: ['Assistant', 'Scrapper', 'Synthesizer'],
        pages: 0,
    },
    {
        id: 'rep_003',
        title: 'AI Ethics in Healthcare Policy Review',
        status: 'completed',
        createdAt: '2026-01-18 02:45 PM',
        agentsUsed: ['Assistant', 'Fact Checker', 'Synthesizer', 'Writer'],
        pages: 18,
    },
    {
        id: 'rep_004',
        title: 'VoltAgent vs LangChain Comparison',
        status: 'failed',
        createdAt: '2026-01-19 04:20 PM',
        agentsUsed: ['Assistant', 'Data Analyzer'],
        pages: 0,
    },
]

export default function ReportsPage() {
    return (
        <div className="flex h-full flex-col gap-6 p-8">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">
                        Research Reports
                    </h1>
                    <p className="text-muted-foreground">
                        View and manage research reports generated by your
                        agents.
                    </p>
                </div>
                <Button className="gap-2">
                    <PlusIcon className="h-4 w-4" />
                    New Report
                </Button>
            </div>

            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Total Reports
                        </CardTitle>
                        <FileTextIcon className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">24</div>
                        <p className="text-xs text-muted-foreground">
                            +3 from last month
                        </p>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Completed
                        </CardTitle>
                        <CheckCircleIcon className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">18</div>
                        <p className="text-xs text-muted-foreground">
                            75% success rate
                        </p>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            In Progress
                        </CardTitle>
                        <ClockIcon className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">4</div>
                        <p className="text-xs text-muted-foreground">
                            Active research sessions
                        </p>
                    </CardContent>
                </Card>
                <Card>
                    <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                        <CardTitle className="text-sm font-medium">
                            Failed
                        </CardTitle>
                        <AlertCircleIcon className="h-4 w-4 text-muted-foreground" />
                    </CardHeader>
                    <CardContent>
                        <div className="text-2xl font-bold">2</div>
                        <p className="text-xs text-muted-foreground">
                            8% failure rate
                        </p>
                    </CardContent>
                </Card>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Recent Reports</CardTitle>
                    <CardDescription>
                        Latest research reports from your agents
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <ScrollArea className="h-[500px]">
                        <div className="space-y-4">
                            {mockReports.map((report) => (
                                <Card
                                    key={report.id}
                                    className="border-2 transition-colors hover:bg-accent"
                                >
                                    <CardContent className="p-6">
                                        <div className="flex items-start justify-between">
                                            <div className="space-y-2 flex-1">
                                                <div className="flex items-center gap-3">
                                                    <h3 className="font-semibold text-lg">
                                                        {report.title}
                                                    </h3>
                                                    <Badge
                                                        variant={
                                                            report.status ===
                                                            'completed'
                                                                ? 'default'
                                                                : report.status ===
                                                                    'in_progress'
                                                                  ? 'secondary'
                                                                  : 'destructive'
                                                        }
                                                    >
                                                        {report.status ===
                                                        'in_progress'
                                                            ? 'In Progress'
                                                            : report.status
                                                                  .charAt(0)
                                                                  .toUpperCase() +
                                                              report.status.slice(
                                                                  1
                                                              )}
                                                    </Badge>
                                                </div>
                                                <div className="flex items-center gap-4 text-sm text-muted-foreground">
                                                    <div className="flex items-center gap-1">
                                                        <ClockIcon className="h-3 w-3" />
                                                        {report.createdAt}
                                                    </div>
                                                    {report.pages > 0 && (
                                                        <div>
                                                            {report.pages} pages
                                                        </div>
                                                    )}
                                                </div>
                                                <div className="flex flex-wrap gap-2">
                                                    {report.agentsUsed.map(
                                                        (agent, i) => (
                                                            <Badge
                                                                key={i}
                                                                variant="outline"
                                                                className="text-xs"
                                                            >
                                                                {agent}
                                                            </Badge>
                                                        )
                                                    )}
                                                </div>
                                            </div>
                                            <div className="flex gap-2">
                                                {report.status ===
                                                    'completed' && (
                                                    <>
                                                        <Button
                                                            size="sm"
                                                            variant="outline"
                                                            className="gap-2"
                                                        >
                                                            <EyeIcon className="h-4 w-4" />
                                                            View
                                                        </Button>
                                                        <Button
                                                            size="sm"
                                                            variant="outline"
                                                            className="gap-2"
                                                        >
                                                            <DownloadIcon className="h-4 w-4" />
                                                            Download
                                                        </Button>
                                                    </>
                                                )}
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>
                            ))}
                        </div>
                    </ScrollArea>
                </CardContent>
            </Card>
        </div>
    )
}
