// Google Gemini models (newest first)
export const googleModels = [
    'google/gemini-3-pro-preview',
    'google/gemini-3-flash-preview',
    'google/gemini-live-2.5-flash-preview-native-audio',
    'google/gemini-live-2.5-flash',
    'google/gemini-2.5-pro-preview-tts',
    'google/gemini-2.5-pro-preview-06-05',
    'google/gemini-2.5-pro-preview-05-06',
    'google/gemini-2.5-pro',
    'google/gemini-2.5-flash-preview-tts',
    'google/gemini-2.5-flash-preview-09-2025',
    'google/gemini-2.5-flash-preview-05-20',
    'google/gemini-2.5-flash-preview-04-17',
    'google/gemini-2.5-flash-lite-preview-09-2025',
    'google/gemini-2.5-flash-lite-preview-06-17',
    'google/gemini-2.5-flash-lite',
    'google/gemini-2.5-flash-image-preview',
    'google/gemini-2.5-flash-image',
    'google/gemini-2.5-flash',
    'google/gemini-flash-lite-latest',
    'google/gemini-flash-latest',
    'google/gemini-2.0-flash-lite',
    'google/gemini-2.0-flash',
    'google/gemini-1.5-flash-8b',
    'google/gemini-1.5-flash',
    'google/gemini-1.5-pro',
    'google/gemini-embedding-001',
]

// OpenAI models (GPT latest at top, then o1-o4, then 4o)
export const openaiModels = [
    // GPT-5 series (latest first)
    'openai/gpt-5.3-codex',
    'openai/gpt-5.2-pro',
    'openai/gpt-5.2-chat-latest',
    'openai/gpt-5.2-codex',
    'openai/gpt-5.2',
    'openai/gpt-5.1-codex-mini',
    'openai/gpt-5.1-codex-max',
    'openai/gpt-5.1-codex',
    'openai/gpt-5.1-chat-latest',
    'openai/gpt-5.1',
    'openai/gpt-5-pro',
    'openai/gpt-5-codex',
    'openai/gpt-5-nano',
    'openai/gpt-5-mini',
    'openai/gpt-5-chat-latest',
    'openai/gpt-5',
    // o-series (o4, o3, o1 - newest first)
    'openai/o4-mini-deep-research',
    'openai/o4-mini',
    'openai/o3-pro',
    'openai/o3-mini',
    'openai/o3-deep-research',
    'openai/o3',
    'openai/o1-pro',
    'openai/o1-mini',
    'openai/o1-preview',
    'openai/o1',
    // GPT-4o series
    'openai/gpt-4o-mini',
    'openai/gpt-4o-2024-11-20',
    'openai/gpt-4o-2024-08-06',
    'openai/gpt-4o-2024-05-13',
    'openai/gpt-4o',
    // Older GPT-4
    'openai/gpt-4.1-nano',
    'openai/gpt-4.1-mini',
    'openai/gpt-4.1',
    'openai/gpt-4-turbo',
    'openai/gpt-4',
    'openai/gpt-3.5-turbo',
    // Embeddings
    'openai/codex-mini-latest',
    'openai/text-embedding-3-large',
    'openai/text-embedding-3-small',
    'openai/text-embedding-ada-002',
]

// Anthropic models (newest first)
export const anthropicModels = [
    'anthropic/claude-opus-4-5-20251101',
    'anthropic/claude-opus-4-20250514',
    'anthropic/claude-opus-4-1-20250805',
    'anthropic/claude-opus-4-1',
    'anthropic/claude-opus-4-0',
    'anthropic/claude-sonnet-4-5-20250929',
    'anthropic/claude-sonnet-4-20250514',
    'anthropic/claude-sonnet-4-0',
    'anthropic/claude-haiku-4-5-20251001',
    'anthropic/claude-haiku-4-5',
    'anthropic/claude-3-7-sonnet-latest',
    'anthropic/claude-3-7-sonnet-20250219',
    'anthropic/claude-3-5-sonnet-20241022',
    'anthropic/claude-3-5-sonnet-20240620',
    'anthropic/claude-3-5-haiku-latest',
    'anthropic/claude-3-5-haiku-20241022',
    'anthropic/claude-3-opus-20240229',
    'anthropic/claude-3-sonnet-20240229',
    'anthropic/claude-3-haiku-20240307',
]

// GitHub Copilot models
export const copilotModels = [
    'github-copilot/claude-opus-4.6',
    'github-copilot/claude-opus-41',
    'github-copilot/claude-opus-4.5',
    'github-copilot/claude-sonnet-4.5',
    'github-copilot/claude-sonnet-4',
    'github-copilot/claude-haiku-4.5',
    'github-copilot/gemini-3-pro-preview',
    'github-copilot/gemini-3-flash-preview',
    'github-copilot/gemini-2.5-pro',
    'github-copilot/gpt-5.3-codex',
    'github-copilot/gpt-5.2-codex',
    'github-copilot/gpt-5.2',
    'github-copilot/gpt-5.1-codex-mini',
    'github-copilot/gpt-5.1-codex-max',
    'github-copilot/gpt-5.1-codex',
    'github-copilot/gpt-5.1',
    'github-copilot/gpt-5-codex',
    'github-copilot/gpt-5-mini',
    'github-copilot/gpt-5',
    'github-copilot/gpt-4o',
    'github-copilot/gpt-4.1',
    'github-copilot/grok-code-fast-1',
]

// OpenCode models
export const opencodeModels = [
    'opencode/kimi-k2.5-free',
    'opencode/minimax-m2.5-free',
    'opencode/alpha-gd4',
    'opencode/alpha-glm-4.7',
    'opencode/big-pickle',
    'opencode/claude-3-5-haiku',
    'opencode/claude-haiku-4-5',
    'opencode/claude-opus-4-1',
    'opencode/claude-opus-4-5',
    'opencode/claude-sonnet-4',
    'opencode/claude-sonnet-4-5',
    'opencode/gemini-3-pro',
    'opencode/gemini-3-flash',
    'opencode/glm-4.7',
    'opencode/gpt-5.2-codex',
    'opencode/gpt-5.2',
    'opencode/gpt-5.1-codex-mini',
    'opencode/gpt-5.1-codex-max',
    'opencode/gpt-5.1-codex',
    'opencode/gpt-5.1',
    'opencode/gpt-5-codex',
    'opencode/gpt-5-nano',
    'opencode/gpt-5-mini',
    'opencode/gpt-5',
    'opencode/grok-code',
    'opencode/kimi-k2-thinking',
    'opencode/kimi-k2',
    'opencode/minimax-m2.1-free',
    'opencode/qwen3-coder',
]

// All models combined
export const allModels = [
    ...googleModels,
    ...openaiModels,
    ...anthropicModels,
    ...copilotModels,
    ...opencodeModels,
]
